### ISSUE TITLE
Forge服务端安装mod后Kubejs脚本出现错误

### ISSUE THREAD

**Issue by 6371peter** [Prunoideae/KubeJS-Curios#1]
问题出现在Forge服务端，单人游戏没问题；Fabric未测试；

Forge版本:1.18.2-40.1.76
KubeJS-Curios版本:kubejs_curios-1.0.0-fix-forge
Curios版本:curios-forge-1.18.2-5.0.7.1
Kubejs版本:kubejs-forge-1802.5.5-build.546
Architectury版本:architectury-4.9.83-forge
Rhino版本:rhino-forge-1802.2.0-build.232

问题：
1.将Kubejs以及Kubejs-curios放入服务端mods文件夹。
2.启动服务端(服务端kubejs文件夹运行服务端后自动生成)。
3.查看logs/kubejs中startup与server，出现报错。

[ERR  ] Failed to read script pack server_scripts: : java.lang.NoClassDefFoundError: com/mojang/blaze3d/vertex/PoseStack
[ERR  ] Failed to read script pack startup_scripts: : java.lang.NoClassDefFoundError: com/mojang/blaze3d/vertex/PoseStack

日志:
[latest.log](https://github.com/Prunoideae/KubeJS-Curios/files/9484566/latest.log)
[startup.txt](https://github.com/Prunoideae/KubeJS-Curios/files/9484599/startup.txt)
[server.txt](https://github.com/Prunoideae/KubeJS-Curios/files/9484601/server.txt)

**Comment by Prunoideae** [comment]
脚本呢，服务端没有PoseStack是很正常的事情，这个是渲染代码
而且PoseStack不应该出现在server_scripts，startup_scripts出现问题倒还能理解

**Comment by 6371peter** [comment]
[script(startup_scripts).txt](https://github.com/Prunoideae/KubeJS-Curios/files/9484620/script.startup_scripts.txt)
[script(server_scripts).txt](https://github.com/Prunoideae/KubeJS-Curios/files/9484621/script.server_scripts.txt)
脚本没修改，直接由服务端运行后生成

**Comment by Prunoideae** [comment]
哦我懂了，这个问题比较麻烦，我过两天修
