### ISSUE TITLE
Changing Entity Attributes using KubeJS causes JEI to take a longer time loading.

### ISSUE THREAD

**Issue by choombdev** [Prunoideae/KubeJS-Curios#2]
I apologize if this isn't the correct place to reach you about this, couldn't find anywhere else. 

I added a few new custom curios to my pack on 1.18.2 (Latest forge, 40.1.82) and they caused a few errors to appear, which in return would stall loading of JEI (In the main pack it takes 25 seconds to load), I believe the issue only happens whenever an attribute is called for in either of  `.onEquipped((stack, entity) => { })` or ` .onWornTick((stack, entity) => { })`. 

Startup Script Files:
https://paste.gg/p/YTGF/2fd0565f56414499b8b8d3200091dbf4

Errors:
https://paste.gg/p/YTGF/2050e2d28e8b416d8e2544adc69e4f3c

Latest and Debug logs - Testing Pack without Curios: 
  - Latest: https://paste.gg/p/YTGF/d2e0dcb5494b4ce480a836d19eaf956a
  - Debug: https://paste.gg/p/YTGF/a534464dac33495ea4880101a1c72db0
Latest and Debug logs - Testing Pack with Curios:
 - Latest: https://paste.gg/p/YTGF/6ff3053572fe4797b7dcf5d1a39126e7
 - Debug: https://paste.gg/p/YTGF/a1e741f18f1d465595963005e6a9bbbe
 
 Testing Pack Modlist:
 [Debugify (by XanderIsDev)](https://www.curseforge.com/minecraft/mc-mods/debugify)
    [Oh The Biomes You'll Go (by AOCAWOL)](https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go)
    [Mystical Customization (by BlakeBr0)](https://www.curseforge.com/minecraft/mc-mods/mystical-customization)
    [Botania (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/botania)
    [Convenient Curios Container (by LeoBeliik)](https://www.curseforge.com/minecraft/mc-mods/convenient-curios-container)
    [Sophisticated Core (by P3pp3rF1y)](https://www.curseforge.com/minecraft/mc-mods/sophisticated-core)
    [Gobber [FORGE] (by kwpugh)](https://www.curseforge.com/minecraft/mc-mods/gobber)
    [Patchouli (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/patchouli)
    [Curios API (Forge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/curios)
    [TerraBlender (Forge) (by TheAdubbz)](https://www.curseforge.com/minecraft/mc-mods/terrablender)
    [Mekanism (by bradyaidanc)](https://www.curseforge.com/minecraft/mc-mods/mekanism)
    [Mystical Agriculture (by BlakeBr0)](https://www.curseforge.com/minecraft/mc-mods/mystical-agriculture)
    [Flywheel (by jozufozu)](https://www.curseforge.com/minecraft/mc-mods/flywheel)
    [Nameless Trinkets (by Cozary)](https://www.curseforge.com/minecraft/mc-mods/nameless-trinkets)
    [Mekanism Generators (by bradyaidanc)](https://www.curseforge.com/minecraft/mc-mods/mekanism-generators)
    [KubeJS Curios (by Amygdaloideae)](https://www.curseforge.com/minecraft/mc-mods/kubejs-curios)
    [Hexerei (by JoeFoxe)](https://www.curseforge.com/minecraft/mc-mods/hexerei)
    [Mystical Agradditions (by BlakeBr0)](https://www.curseforge.com/minecraft/mc-mods/mystical-agradditions)
    [Almost Unified (by TeamAlmostReliable)](https://www.curseforge.com/minecraft/mc-mods/almost-unified)
    [Hex Casting (by petrak_at)](https://www.curseforge.com/minecraft/mc-mods/hexcasting)
    [Sophisticated Backpacks (by P3pp3rF1y)](https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks)
    [Architectury API (Fabric/Forge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/architectury-api)
    [Rhino (by LatvianModder)](https://www.curseforge.com/minecraft/mc-mods/rhino)
    [PAUCAL (by petrak_at)](https://www.curseforge.com/minecraft/mc-mods/paucal)
    [Health Overlay (Forge) (by Terrails)](https://www.curseforge.com/minecraft/mc-mods/health-overlay)
    [Create (by simibubi)](https://www.curseforge.com/minecraft/mc-mods/create)
    [Simple Storage Network (by Lothrazar)](https://www.curseforge.com/minecraft/mc-mods/simple-storage-network)
    [Just Enough Items (JEI) (by mezz)](https://www.curseforge.com/minecraft/mc-mods/jei)
    [Cucumber Library (by BlakeBr0)](https://www.curseforge.com/minecraft/mc-mods/cucumber)
    [KubeJS (by LatvianModder)](https://www.curseforge.com/minecraft/mc-mods/kubejs)
    [Cloth Config API (Fabric/Forge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/cloth-config)
    [AppleSkin (by squeek502)](https://www.curseforge.com/minecraft/mc-mods/appleskin)
    [Kotlin for Forge (by thedarkcolour)](https://www.curseforge.com/minecraft/mc-mods/kotlin-for-forge)
    [Overloaded Armor Bar (by tfarecnim)](https://www.curseforge.com/minecraft/mc-mods/overloaded-armor-bar)
    [Fuze's Relics (by Furti_Two)](https://www.curseforge.com/minecraft/mc-mods/fuzes-relics)
 
 If this is an issue on my part, let me know, this mod has been a great help so far, just hope I can get this fixed.

**Comment by Prunoideae** [comment]
Fixed in recent commit, a fix version will be pushed after Monday. I've been super busy recently, so can't work out things so fast, sorry.
