### ISSUE TITLE
在Quilt端安装会使startup脚本失效

### ISSUE THREAD

**Issue by orange809** [Prunoideae/KubeJS-Curios#3]
问题:
进入游戏后会使startup脚本失效

报错:
startup.txt:
 [ERR  ] Failed to read script pack startup_scripts: : java.lang.NullPointerException: Cannot invoke "com.prunoideae.curios.fabric.KubeJSCuriosFabricCommon.clientBindings(dev.latvian.mods.kubejs.script.BindingsEvent)" because "com.prunoideae.curios.fabric.KubeJSCuriosFabric.PROXY" is null

日志:
[latest.log](https://github.com/Prunoideae/KubeJS-Curios/files/10471375/latest.log)
[startup.txt](https://github.com/Prunoideae/KubeJS-Curios/files/10471377/startup.txt)
[server.txt](https://github.com/Prunoideae/KubeJS-Curios/files/10471378/server.txt)

Quilt版本:1.18.2-0.18.1-beta.30
KubeJS-Curios版本:kubejs_curios-1.0.1-fabric
Trinkets版本:trinkets-3.3.1
Kubejs版本:kubejs-fabric-1802.5.5-build.546
Architectury版本:architectury-4.10.88-fabric
Rhino版本:rhino-fabric-1802.2.1-build.255

**Comment by Prunoideae** [comment]
这个Mod暂时不会有维护了，最近研究工作比较忙
